
package com.hqc.payforparking.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceForPaySoap", targetNamespace = "http://www.keytop.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceForPaySoap {


    /**
     *  1 停车场列表查询接口
     * 
     * @param appId
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingLotList", action = "http://www.keytop.com.cn/GetParkingLotList")
    @WebResult(name = "GetParkingLotListResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingLotList", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotList")
    @ResponseWrapper(localName = "GetParkingLotListResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotListResponse")
    public String getParkingLotList(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key);

    /**
     *  2 停车场信息查询接口
     * 
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingLotInfo", action = "http://www.keytop.com.cn/GetParkingLotInfo")
    @WebResult(name = "GetParkingLotInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingLotInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotInfo")
    @ResponseWrapper(localName = "GetParkingLotInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotInfoResponse")
    public String getParkingLotInfo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId);

    /**
     *  3 车流量查询接口
     * 
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTrafficNum", action = "http://www.keytop.com.cn/GetTrafficNum")
    @WebResult(name = "GetTrafficNumResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetTrafficNum", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetTrafficNum")
    @ResponseWrapper(localName = "GetTrafficNumResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetTrafficNumResponse")
    public String getTrafficNum(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId);

    /**
     *  4 停车费(账单)查询接口
     * 
     * @param plateNo
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingPaymentInfo", action = "http://www.keytop.com.cn/GetParkingPaymentInfo")
    @WebResult(name = "GetParkingPaymentInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingPaymentInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingPaymentInfo")
    @ResponseWrapper(localName = "GetParkingPaymentInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingPaymentInfoResponse")
    public String getParkingPaymentInfo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo);

    /**
     *  4.1 停车费(账单)查询接口(增加停车区域)
     * 
     * @param plateNo
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingPaymentInfo2", action = "http://www.keytop.com.cn/GetParkingPaymentInfo2")
    @WebResult(name = "GetParkingPaymentInfo2Result", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingPaymentInfo2", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingPaymentInfo2")
    @ResponseWrapper(localName = "GetParkingPaymentInfo2Response", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingPaymentInfo2Response")
    public String getParkingPaymentInfo2(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo);

    /**
     *  4.2 账单减免计费接口
     * 
     * @param orderId
     * @param appId
     * @param freeTime
     * @param key
     * @param freeMoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPaymentRecharge", action = "http://www.keytop.com.cn/GetPaymentRecharge")
    @WebResult(name = "GetPaymentRechargeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetPaymentRecharge", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetPaymentRecharge")
    @ResponseWrapper(localName = "GetPaymentRechargeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetPaymentRechargeResponse")
    public String getPaymentRecharge(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderId", targetNamespace = "http://www.keytop.com.cn/")
        String orderId,
        @WebParam(name = "freeMoney", targetNamespace = "http://www.keytop.com.cn/")
        int freeMoney,
        @WebParam(name = "freeTime", targetNamespace = "http://www.keytop.com.cn/")
        int freeTime);

    /**
     *  5.1 停车费支付(账单同步)接口 旧版
     * 
     * @param amount
     * @param orderNo
     * @param appId
     * @param discount
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee", action = "http://www.keytop.com.cn/PayParkingFee")
    @WebResult(name = "PayParkingFeeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFee")
    @ResponseWrapper(localName = "PayParkingFeeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFeeResponse")
    public String payParkingFee(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
        int amount,
        @WebParam(name = "discount", targetNamespace = "http://www.keytop.com.cn/")
        int discount);

    /**
     *  5.2 停车费支付(账单同步)接口 微信支付
     * 
     * @param amount
     * @param orderNo
     * @param appId
     * @param discount
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee_Wec", action = "http://www.keytop.com.cn/PayParkingFee_Wec")
    @WebResult(name = "PayParkingFee_WecResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee_Wec", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFeeWec")
    @ResponseWrapper(localName = "PayParkingFee_WecResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFeeWecResponse")
    public String payParkingFeeWec(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
        int amount,
        @WebParam(name = "discount", targetNamespace = "http://www.keytop.com.cn/")
        int discount);

    /**
     *  5.3 停车费支付(账单同步)接口 支付宝支付
     * 
     * @param amount
     * @param orderNo
     * @param appId
     * @param discount
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee_Alipay", action = "http://www.keytop.com.cn/PayParkingFee_Alipay")
    @WebResult(name = "PayParkingFee_AlipayResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee_Alipay", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFeeAlipay")
    @ResponseWrapper(localName = "PayParkingFee_AlipayResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFeeAlipayResponse")
    public String payParkingFeeAlipay(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
        int amount,
        @WebParam(name = "discount", targetNamespace = "http://www.keytop.com.cn/")
        int discount);

    /**
     *  5.4 停车费支付(账单同步)接口 
     * 
     * @param amount
     * @param orderNo
     * @param payType
     * @param payMethod
     * @param appId
     * @param freeTime
     * @param freeDetail
     * @param key
     * @param freeMoney
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayParkingFee2", action = "http://www.keytop.com.cn/PayParkingFee2")
    @WebResult(name = "PayParkingFee2Result", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayParkingFee2", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFee2")
    @ResponseWrapper(localName = "PayParkingFee2Response", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayParkingFee2Response")
    public String payParkingFee2(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
        int amount,
        @WebParam(name = "payType", targetNamespace = "http://www.keytop.com.cn/")
        int payType,
        @WebParam(name = "payMethod", targetNamespace = "http://www.keytop.com.cn/")
        int payMethod,
        @WebParam(name = "freeMoney", targetNamespace = "http://www.keytop.com.cn/")
        int freeMoney,
        @WebParam(name = "freeTime", targetNamespace = "http://www.keytop.com.cn/")
        int freeTime,
        @WebParam(name = "freeDetail", targetNamespace = "http://www.keytop.com.cn/")
        String freeDetail);

    /**
     *  6 在场车辆模糊查询接口
     * 
     * @param plateNo
     * @param pageIndex
     * @param appId
     * @param startTime
     * @param endTime
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingCarInfo", action = "http://www.keytop.com.cn/GetParkingCarInfo")
    @WebResult(name = "GetParkingCarInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingCarInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingCarInfo")
    @ResponseWrapper(localName = "GetParkingCarInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingCarInfoResponse")
    public String getParkingCarInfo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo,
        @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
        String endTime,
        @WebParam(name = "pageIndex", targetNamespace = "http://www.keytop.com.cn/")
        String pageIndex);

    /**
     *  7 根据车牌号确定停车场接口
     * 
     * @param plateNo
     * @param appId
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetParkingLotByCar", action = "http://www.keytop.com.cn/GetParkingLotByCar")
    @WebResult(name = "GetParkingLotByCarResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetParkingLotByCar", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotByCar")
    @ResponseWrapper(localName = "GetParkingLotByCarResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetParkingLotByCarResponse")
    public String getParkingLotByCar(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo);

    /**
     *  8 固定车查询接口
     * 
     * @param plateNo
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarCardInfo", action = "http://www.keytop.com.cn/GetCarCardInfo")
    @WebResult(name = "GetCarCardInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarCardInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardInfo")
    @ResponseWrapper(localName = "GetCarCardInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardInfoResponse")
    public String getCarCardInfo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo);

    /**
     *  9 固定车充值规则查询接口
     * 
     * @param carType
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarCardRule", action = "http://www.keytop.com.cn/GetCarCardRule")
    @WebResult(name = "GetCarCardRuleResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarCardRule", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardRule")
    @ResponseWrapper(localName = "GetCarCardRuleResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardRuleResponse")
    public String getCarCardRule(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "carType", targetNamespace = "http://www.keytop.com.cn/")
        int carType);

    /**
     *  9 固定车充值规则查询接口(根据ID)
     * 
     * @param appId
     * @param ruleId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarCardRule2", action = "http://www.keytop.com.cn/GetCarCardRule2")
    @WebResult(name = "GetCarCardRule2Result", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarCardRule2", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardRule2")
    @ResponseWrapper(localName = "GetCarCardRule2Response", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardRule2Response")
    public String getCarCardRule2(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "ruleId", targetNamespace = "http://www.keytop.com.cn/")
        int ruleId);

    /**
     *  10 固定车充值订单查询接口
     * 
     * @param chargeCount
     * @param appId
     * @param cardId
     * @param ruleId
     * @param key
     * @param parkId
     * @param chargeFrom
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCarCardFee", action = "http://www.keytop.com.cn/GetCarCardFee")
    @WebResult(name = "GetCarCardFeeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetCarCardFee", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardFee")
    @ResponseWrapper(localName = "GetCarCardFeeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetCarCardFeeResponse")
    public String getCarCardFee(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "cardId", targetNamespace = "http://www.keytop.com.cn/")
        int cardId,
        @WebParam(name = "ruleId", targetNamespace = "http://www.keytop.com.cn/")
        int ruleId,
        @WebParam(name = "chargeFrom", targetNamespace = "http://www.keytop.com.cn/")
        String chargeFrom,
        @WebParam(name = "chargeCount", targetNamespace = "http://www.keytop.com.cn/")
        int chargeCount);

    /**
     *  11 固定车充值接口
     * 
     * @param amount
     * @param orderNo
     * @param appId
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PayCarCardFee", action = "http://www.keytop.com.cn/PayCarCardFee")
    @WebResult(name = "PayCarCardFeeResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "PayCarCardFee", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayCarCardFee")
    @ResponseWrapper(localName = "PayCarCardFeeResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.PayCarCardFeeResponse")
    public String payCarCardFee(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "amount", targetNamespace = "http://www.keytop.com.cn/")
        int amount);

    /**
     *  12 获取空余车位数接口
     * 
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetFreeSpaceNum", action = "http://www.keytop.com.cn/GetFreeSpaceNum")
    @WebResult(name = "GetFreeSpaceNumResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetFreeSpaceNum", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetFreeSpaceNum")
    @ResponseWrapper(localName = "GetFreeSpaceNumResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetFreeSpaceNumResponse")
    public String getFreeSpaceNum(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId);

    /**
     *  13 获取空余车位数接口
     * 
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAreaFreeSpace", action = "http://www.keytop.com.cn/GetAreaFreeSpace")
    @WebResult(name = "GetAreaFreeSpaceResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetAreaFreeSpace", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetAreaFreeSpace")
    @ResponseWrapper(localName = "GetAreaFreeSpaceResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetAreaFreeSpaceResponse")
    public String getAreaFreeSpace(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId);

    /**
     *  14 车场统计数据查询接口
     * 
     * @param appId
     * @param startTime
     * @param endTime
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReportInfo", action = "http://www.keytop.com.cn/GetReportInfo")
    @WebResult(name = "GetReportInfoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetReportInfo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetReportInfo")
    @ResponseWrapper(localName = "GetReportInfoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetReportInfoResponse")
    public String getReportInfo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "startTime", targetNamespace = "http://www.keytop.com.cn/")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "http://www.keytop.com.cn/")
        String endTime);

    /**
     *  15 积分抵扣(定制)
     * 
     * @param orderNo
     * @param dValue
     * @param appId
     * @param dType
     * @param key
     * @param points
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MemberDeduction", action = "http://www.keytop.com.cn/MemberDeduction")
    @WebResult(name = "MemberDeductionResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "MemberDeduction", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.MemberDeduction")
    @ResponseWrapper(localName = "MemberDeductionResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.MemberDeductionResponse")
    public String memberDeduction(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "orderNo", targetNamespace = "http://www.keytop.com.cn/")
        String orderNo,
        @WebParam(name = "points", targetNamespace = "http://www.keytop.com.cn/")
        int points,
        @WebParam(name = "dType", targetNamespace = "http://www.keytop.com.cn/")
        int dType,
        @WebParam(name = "dValue", targetNamespace = "http://www.keytop.com.cn/")
        int dValue);

    /**
     *  16停车场设备状态查询接口
     * 
     * @param appId
     * @param key
     * @param parkId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeviceStatusList", action = "http://www.keytop.com.cn/GetDeviceStatusList")
    @WebResult(name = "GetDeviceStatusListResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "GetDeviceStatusList", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetDeviceStatusList")
    @ResponseWrapper(localName = "GetDeviceStatusListResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.GetDeviceStatusListResponse")
    public String getDeviceStatusList(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId);

    /**
     *  17 添加固定车(定制)
     * 
     * @param etcNo
     * @param carType
     * @param plateNo
     * @param appId
     * @param validFrom
     * @param key
     * @param parkId
     * @param validTo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddCarCardNo", action = "http://www.keytop.com.cn/AddCarCardNo")
    @WebResult(name = "AddCarCardNoResult", targetNamespace = "http://www.keytop.com.cn/")
    @RequestWrapper(localName = "AddCarCardNo", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.AddCarCardNo")
    @ResponseWrapper(localName = "AddCarCardNoResponse", targetNamespace = "http://www.keytop.com.cn/", className = "com.hqc.payforparking.ws.AddCarCardNoResponse")
    public String addCarCardNo(
        @WebParam(name = "appId", targetNamespace = "http://www.keytop.com.cn/")
        int appId,
        @WebParam(name = "key", targetNamespace = "http://www.keytop.com.cn/")
        String key,
        @WebParam(name = "parkId", targetNamespace = "http://www.keytop.com.cn/")
        int parkId,
        @WebParam(name = "plateNo", targetNamespace = "http://www.keytop.com.cn/")
        String plateNo,
        @WebParam(name = "etcNo", targetNamespace = "http://www.keytop.com.cn/")
        String etcNo,
        @WebParam(name = "carType", targetNamespace = "http://www.keytop.com.cn/")
        int carType,
        @WebParam(name = "ValidFrom", targetNamespace = "http://www.keytop.com.cn/")
        String validFrom,
        @WebParam(name = "ValidTo", targetNamespace = "http://www.keytop.com.cn/")
        String validTo);

}
