
package com.hqc.payforparking.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceForPay", targetNamespace = "http://www.keytop.com.cn/", wsdlLocation = "http://220.160.111.114:8099/webserviceforpay.asmx?WSDL")
public class WebServiceForPay
    extends Service
{

    private final static URL WEBSERVICEFORPAY_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEFORPAY_EXCEPTION;
    private final static QName WEBSERVICEFORPAY_QNAME = new QName("http://www.keytop.com.cn/", "WebServiceForPay");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://220.160.111.114:8099/webserviceforpay.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEFORPAY_WSDL_LOCATION = url;
        WEBSERVICEFORPAY_EXCEPTION = e;
    }

    public WebServiceForPay() {
        super(__getWsdlLocation(), WEBSERVICEFORPAY_QNAME);
    }

    public WebServiceForPay(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEFORPAY_QNAME, features);
    }

    public WebServiceForPay(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEFORPAY_QNAME);
    }

    public WebServiceForPay(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEFORPAY_QNAME, features);
    }

    public WebServiceForPay(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceForPay(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap")
    public WebServiceForPaySoap getWebServiceForPaySoap() {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap"), WebServiceForPaySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceForPaySoap
     */
    @WebEndpoint(name = "WebServiceForPaySoap")
    public WebServiceForPaySoap getWebServiceForPaySoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.keytop.com.cn/", "WebServiceForPaySoap"), WebServiceForPaySoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEFORPAY_EXCEPTION!= null) {
            throw WEBSERVICEFORPAY_EXCEPTION;
        }
        return WEBSERVICEFORPAY_WSDL_LOCATION;
    }

}
